length:
  min_5: 5
  min_8: 8
  max_100: 100
  max_250: 250
show:
  show_5: 5
  show_10: 10
  digit_1: 1
  digit_8: 8
open: 0
confirmed: 1
shipping: 2
completed: 3
cancelled: 4
disabled: 0
enabled: 1
gravatar:
  size_50: 50
  size_80: 80
per_page_15: 15
